apiVersion: apps/v1
kind: Deployment
metadata:
  name: msemailservices
  labels:
    app: msemailservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msemailservices
  template:
    metadata:
      labels:
        app: msemailservices
    spec:
      containers:
      - name: msemailservices
        image: http://gcr.io/google-samples/microservices-demo/emailservice
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
  - protocol : TCP
    port: 5000
    targetPort: 8080